version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
      - "npm"
    commit-message:
      prefix: "deps(frontend-npm)"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(frontend-actions)"
    groups:
      actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
